name: ImperialItems
version: '${project.version}'
main: ru.imperiamc.imperialitems.ImperialItems
api-version: 1.19
authors: [ twistofthemyth ]
website: imperia-mc.ru
commands:
  ii:
    description: add item replacement rule
    usage: /<command>
  ii add:
    description: add item replacement rule
    usage: /<command>
