name: ImperialItems
version: '${project.version}'
main: ru.imperiamc.imperialitems.ImperialItems
api-version: 1.19
authors: [ twistofthemyth ]
website: imperia-mc.ru
permissions:
  imperialitems.admin:
    description: access to admin commands
    default: false
commands:
  ii:
    description: add item replacement rule
    usage: /<command>
  ii add reference:
    description: add item held on main hand as replacement rule
    usage: /<command>
  ii remove reference:
    description: remove item held on main hand from replacement rules
    usage: /<command>
  ii add recipe:
    description: adds item held on main hand as recipe component
    usage: /<command> <component name>
  ii remove recipe:
    description: remove recipe component
    usage: /<command> <component name>

