name: ImperialItems
version: '${project.version}'
main: ru.imperiamc.imperialitems.ImperialItems
api-version: 1.19
authors: [ twistofthemyth ]
website: imperia-mc.ru
permissions:
  imperialitems.admin:
    description: access to admin commands
    default: false
commands:
  ii:
    description: add item replacement rule
    usage: /<command>
  ii add:
    description: add item replacement rule
    usage: /<command>
  ii addlore:
    description: add item replacement rule
    usage: /<command>
  ii addalore:
    description: add item replacement rule
    usage: /<command>
  ii reload:
    description: add item replacement rule
    usage: /<command>
  ii addrecipe:
    description: adds item held on main hand as recipe component
    usage: /<command> <component name>
